kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: kola-test-jenkins-trigger
spec:
  params:
    - name: JENKINS_HOST_URL
      type: string
    - name: JOB_NAME
      type: string
    - description: 'Snapshot of the konflux application'
      name: SNAPSHOT
      type: string
  tasks:
    - name: kola-tests-jenkins-job
      taskRef:
        resolver: "git"
        params:
        - name: url
          value: https://github.com/konflux-ci/tekton-integration-catalog.git
        - name: revision
          value: main
        - name: pathInRepo
          value: tasks/triggers/jenkins/0.1/trigger-jenkins-job.yaml
      params:
        - name: JENKINS_HOST_URL
          value: $(params.JENKINS_HOST_URL)
        - name: JOB_NAME
          value: $(params.JOB_NAME)
        - name: JENKINS_SECRETS
          value: fcos-jenkins-staging
        - name: JOB_PARAMS
          value:
          - SOURCE_OCI_IMAGE=$(params.SNAPSHOT)
          - NO_UPLOAD=true
